name: enactus_bue_flutter_team2
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  iconsax: ^0.0.8
  
  get: ^4.6.5
  get_storage: ^2.1.1

  
  flutter_lints: ^5.0.0



flutter:

 
  uses-material-design: true

  
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/



  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/kanit-Regular.ttf
        
    - family: PlayFair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf     
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
        
 

