class PlantDetailsList {
    final List<Map<String, dynamic>> plants = [
    {"name": "Aloe Vera", "price": 15, "image": "assets/images/1.png", "details" : "Aloe Vera is a succulent plant species of the genus Aloe. An evergreen perennial, it originates from the Arabian Peninsula, but grows wild in tropical, semi-tropical, and arid climates around the world. It is cultivated for agricultural and medicinal uses."},
    {"name": "Snake Plant", "price": 20, "image": "assets/images/2.png","details" : "Sansevieria trifasciata is a species of flowering plant in the family Asparagaceae, native to tropical West Africa from Nigeria east to the Congo. It is most commonly known as the snake plant, Saint George's sword, mother-in-law's tongue, and viper's bowstring hemp, among other names."},
    {"name": "Peace Lily", "price": 25, "image": "assets/images/3.png","details" : "Spathiphyllum is a genus of about 47 species of monocotyledonous flowering plants in the family Araceae, native to tropical regions of the Americas and southeastern Asia. Certain species of Spathiphyllum are commonly known as spath or peace lilies."},
    {"name": "Bamboo Plant", "price": 40, "image": "assets/images/4.png","details" : "Bamboo is a group of woody perennial grasses in the true grass family Poaceae, which is a large and nearly ubiquitous family of monocotyledonous flowering plants. The word 'bamboo' comes from the Dutch or Portuguese languages, which probably borrowed it from Malay."},
    {"name": "Cactus", "price": 18, "image": "assets/images/5.png","details" : "A cactus is a member of the plant family Cactaceae, a family comprising about 127 genera with some 1750 known species of the order Caryophyllales. The word 'cactus' derives, through Latin, from the Ancient Greek κάκτος, kaktos, a name originally used by Theophrastus for a spiny plant whose identity is now not certain."},
    {"name": "Fern", "price": 22, "image": "assets/images/6.png","details" : "A fern is a member of a group of vascular plants that reproduce via spores and have neither seeds nor flowers. They differ from mosses by being vascular, i.e., having specialized tissues that conduct water and nutrients and in having life cycles in which the sporophyte is the dominant phase."},
    {"name": "Orchid", "price": 30, "image": "assets/images/7.png","details" : "The Orchidaceae are a diverse and widespread family of flowering plants, with blooms that are often colourful and fragrant, commonly known as the orchid family. Along with the Asteraceae, they are one of the two largest families of flowering plants, with between 21,950 and 26,049 currently accepted species, found in 880 genera."},
    {"name": "Bonsai Tree", "price": 28, "image": "assets/images/8.png","details" : "Bonsai is a Japanese art form which utilizes cultivation techniques to produce, in containers, small trees that mimic the shape and scale of full size trees. Similar practices exist in other cultures, including the Chinese tradition of penjing from which the art originated, and the miniature living landscapes of Vietnamese hòn non bộ."},
  ];
}

